name: Deployment
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: 'build'
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.18.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.0'

    - name: Install dependencies
      run: yarn

    - name: Build static site
      run: yarn build

    - name: Deploy staging
      if: github.ref == 'refs/heads/develop'
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
        REACT_APP_CHAIN_ID: ${{ secrets.REACT_APP_CHAIN_ID_STAGING }}
        REACT_APP_NETWORK_ID: ${{ secrets.REACT_APP_NETWORK_ID_STAGING }}
        REACT_APP_NETWORK_URL: ${{ secrets.REACT_APP_NETWORK_URL_STAGING }}

    - name: Deploy production
      if: github.ref == 'refs/heads/master'
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}
        REACT_APP_CHAIN_ID: ${{ secrets.REACT_APP_CHAIN_ID_PRODUCTION }}
        REACT_APP_NETWORK_ID: ${{ secrets.REACT_APP_NETWORK_ID_PRODUCTION }}
        REACT_APP_NETWORK_URL: ${{ secrets.REACT_APP_NETWORK_URL_PRODUCTION }}
