name: Staging Deployment
on:
    push:
        branches:
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            SOURCE_DIR: 'build'
            AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            REACT_APP_GRAPH_API_URLS: ${{ secrets.REACT_APP_GRAPH_API_URLS_STAGING }}
            REACT_APP_NETWORK_ID: ${{ secrets.REACT_APP_NETWORK_ID_STAGING }}
            REACT_APP_NETWORK_URL: ${{ secrets.REACT_APP_NETWORK_URL_STAGING }}
            REACT_APP_SYSTEM_STATUS: ${{ secrets.REACT_APP_SYSTEM_STATUS_STAGING }}
            REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.REACT_APP_GOOGLE_ANALYTICS_ID_STAGING }}
            REACT_APP_SHOW_AUCTIONS: ${{ secrets.REACT_APP_SHOW_AUCTIONS_STAGING }}
            REACT_APP_WYRE_WORKER: ${{ secrets.REACT_APP_WYRE_WORKER }}

        steps:
            - uses: actions/checkout@v2

            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build static site
              run: yarn build

            - name: Deploy staging
              uses: jakejarvis/s3-sync-action@v0.5.0
              with:
                  args: --acl public-read --follow-symlinks --delete
